config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users

  resources :departments
  resources :positions
  resources :applicants
  scope :profile do
    resources :users
  end

  namespace :api do
    mount_devise_token_auth_for 'User', at: '/v1/auth'
    namespace :v1 do
      resources :departments
      resources :positions
      resources :applicants
      namespace :profile do
        resources :users
      end
    end
  end
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :users, dependent: :restrict_with_error

  validates :title, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/api/v1/positions_controller.rb
module Api
  module V1
    class PositionsController < Api::V1::BaseApiController
      before_action :find_position, only: [:show, :update, :destroy]

      def index
        positions = Position.all
        json_response(positions)
      end

      def show
        json_response(@position)
      end

      def create
        position = Position.create!(position_params)
        json_response(position, :created)
      end

      def update
        @position.update!(position_params)
        json_response(@position)
      end

      def destroy
        @position.destroy
        head :no_content
      end

      private

      def position_params
        params.permit(:title, :description)
      end

      def find_position
        @position = Position.find(params[:id])
      end
    end
  end
end

app/controllers/positions_controller.rb
class PositionsController < BaseController
  before_action :find_position, only: [:show, :edit, :update, :destroy]
  def index
    @positions = Position.all
  end

  def new
    @position = Position.new
  end

  def show
  end

  def create
    @position = Position.new(position_params)
    if @position.save
      redirect_to @position
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @position.update(position_params)
      redirect_to @position
    else
      render :edit
    end
  end

  def destroy
    @position.destroy
    redirect_to positions_path
  end

  private

  def position_params
    params.require(:position).permit(:title, :description)
  end

  def find_position
    @position = Position.find(params[:id])
  end
end

app/views/positions/_form.haml
= simple_form_for @position do |f|
  = f.input :title
  = f.input :description, as: :text
  = f.button :submit
  = link_to 'Cancel', positions_path

app/views/positions/edit.haml
%h3 Edit Position
= render 'form'

app/views/positions/index.haml
%h3 Position list

= link_to 'Add new position', new_position_path

%table
  %tr
    %th Name
    %th Description
    %th{ colspan: '2' } Action
  - @positions.each do |position|
    %tr
      %td= position.title
      %td= position.description
      %td= link_to 'Edit', edit_position_path(position)
      %td= link_to 'Delete', position_path(position), method: :delete, data: { confirm: 'Are you sure you want to delete?' }

app/views/positions/new.haml
%h3 New Position
= render 'form'

app/views/positions/show.haml
%h3 Position detail
%p= "Name: #{@position.title}"
%p= "Description: #{@position.description}"
%p= link_to 'Back to list', positions_path