config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users

  resources :departments
  resources :positions
  resources :applicants
  scope :profile do
    resources :users
  end

  namespace :api do
    mount_devise_token_auth_for 'User', at: '/v1/auth'
    namespace :v1 do
      resources :departments
      resources :positions
      resources :applicants
      namespace :profile do
        resources :users
      end
    end
  end
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  INTERVIEW_RESULTS = ['passed', 'failed'].freeze
  INTERVIEW_STATUSES = ['pending', 'shortlist', 'done'].freeze
  INVITATION_STATUSES = ['pending', 'invited'].freeze

  validates :name, :interview_date, :phone, presence: true
  validates :phone, :email, presence: true, uniqueness: { case_sensitive: false }
  validates :interview_result, presence: true, if: :done_interviewing?

  private

  def done_interviewing?
    interview_status == 'done'
  end
end

app/controllers/api/v1/applicants_controller.rb
module Api
  module V1
    class ApplicantsController < Api::V1::BaseApiController
      before_action :find_applicant, only: [:show, :update, :destroy]

      def index
        applicants = Applicant.all
        json_response(applicants)
      end

      def show
        json_response(@applicant)
      end

      def create
        applicant = Applicant.create!(applicant_params)
        json_response(applicant, :created)
      end

      def update
        @applicant.update!(applicant_params)
        json_response(@applicant)
      end

      def destroy
        @applicant.destroy
        head :no_content
      end

      private

      def applicant_params
        params.permit(:name, :email, :phone, :interview_status, :interview_date, :interview_result, :invitation_status)
      end

      def find_applicant
        @applicant = Applicant.find(params[:id])
      end
    end
  end
end

app/controllers/applicants_controller.rb
class ApplicantsController < BaseController
  before_action :find_applicant, only: [:show, :edit, :update, :destroy]
  def index
    @applicants = Applicant.all
  end

  def new
    @applicant = Applicant.new
  end

  def show
  end

  def create
    @applicant = Applicant.new(applicant_params)
    if @applicant.save
      redirect_to @applicant
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @applicant.update(applicant_params)
      redirect_to @applicant
    else
      render :edit
    end
  end

  def destroy
    @applicant.destroy
    redirect_to applicants_path
  end

  private

  def applicant_params
    params.require(:applicant).permit(:name, :email, :phone, :interview_status, :interview_date, :interview_result, :invitation_status)
  end

  def find_applicant
    @applicant = Applicant.find(params[:id])
  end
end

app/views/applicants/_form.haml
= simple_form_for @applicant do |f|
  = f.input :name
  = f.input :email
  = f.input :phone
  = f.input :interview_date
  = f.input :interview_status
  = f.input :invitation_status
  = f.button :submit
  = link_to 'Cancel', applicants_path

app/views/applicants/edit.haml
%h3 Edit Applicant
= render 'form'

app/views/applicants/index.haml
%h3 Applicant list

= link_to 'Add new applicant', new_applicant_path

%table
  %tr
    %th Name
    %th Email
    %th Phone
    %th Interview date
    %th Interview status
    %th Invitation status
    %th{ colspan: '2' } Action
  - @applicants.each do |applicant|
    %tr
      %td= applicant.name
      %td= applicant.email
      %td= applicant.phone
      %td= applicant.interview_date
      %td= applicant.interview_status
      %td= applicant.invitation_status
      %td= link_to 'Edit', edit_applicant_path(applicant)
      %td= link_to 'Delete', applicant_path(applicant), method: :delete, data: { confirm: 'Are you sure you want to delete?' }

app/views/applicants/new.haml
%h3 New Applicant
= render 'form'

app/views/applicants/show.haml
%h3 Applicant detail
%p= "Name: #{@applicant.name}"
%p= "Email: #{@applicant.email}"
%p= "Phone: #{@applicant.phone}"
%p= "Interview date: #{@applicant.interview_date}"
%p= "Interview status: #{@applicant.interview_status}"
%p= "Invitation status: #{@applicant.invitation_status}"
%p= link_to 'Back to list', applicants_path