config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users

  resources :departments
  resources :positions
  resources :applicants
  scope :profile do
    resources :users
  end

  namespace :api do
    mount_devise_token_auth_for 'User', at: '/v1/auth'
    namespace :v1 do
      resources :departments
      resources :positions
      resources :applicants
      namespace :profile do
        resources :users
      end
    end
  end
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :users, dependent: :restrict_with_error

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/api/v1/departments_controller.rb
module Api
  module V1
    class DepartmentsController < Api::V1::BaseApiController
      before_action :find_department, only: [:show, :update, :destroy]
      def index
        @departments = Department.all
        json_response(@departments)
      end

      def show
        json_response(@department)
      end

      def create
        department = Department.create!(department_params)
        json_response(department, :created)
      end

      def update
        @department.update!(department_params)
        json_response(@department)
      end

      def destroy
        @department.destroy
        head :no_content
      end

      private

      def department_params
        params.permit(:name, :description)
      end

      def find_department
        @department = Department.find(params[:id])
      end
    end
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < BaseController
  before_action :find_department, only: [:show, :edit, :update, :destroy]
  def index
    @departments = Department.all
  end

  def new
    @department = Department.new
  end

  def show
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to @department
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @department.update(department_params)
      redirect_to @department
    else
      render :edit
    end
  end

  def destroy
    @department.destroy
    redirect_to departments_path
  end

  private

  def department_params
    params.require(:department).permit(:name, :description)
  end

  def find_department
    @department = Department.find(params[:id])
  end
end

app/views/departments/_form.haml
= simple_form_for @department do |f|
  = f.input :name
  = f.input :description, as: :text
  = f.button :submit
  = link_to 'Cancel', departments_path

app/views/departments/edit.haml
%h3 Edit Department
= render 'form'

app/views/departments/index.haml
%h3 Department list

= link_to 'Add new department', new_department_path

%table
  %tr
    %th Name
    %th Description
    %th{ colspan: '2' } Action
  - @departments.each do |department|
    %tr
      %td= department.name
      %td= department.description
      %td= link_to 'Edit', edit_department_path(department)
      %td= link_to 'Delete', department_path(department), method: :delete, data: { confirm: 'Are you sure you want to delete?' }

app/views/departments/new.haml
%h3 New Department
= render 'form'

app/views/departments/show.haml
%h3 Department detail
%p= "Name: #{@department.name}"
%p= "Description: #{@department.description}"
%p= link_to 'Back to list', departments_path